development:
  adapter: postgresql
  database: bookstore_db_dev
  pool: 5
  timeout: 5000
test:
  adapter: postgresql
  database: bookstore_db_tst
  pool: 5
  timeout: 5000

production:
  adapter: postgresql
  database: bookstore_db_prd
  pool: 5
  timeout: 5000